version: '3.7'

services:
  ems-service:
    image: operation-agent
    container_name: operation-agent
    restart: unless-stopped
    volumes:
      - /home/hankliang/data/operation-agent/logs:/home/app/workdir/data/logs
      - /home/hankliang/data/operation-agent/workflow_graphs:/home/app/workdir/data/workflow_graphs
    env_file:
      - ./agent.env
    ports:
      - "8601:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
        test: curl -fs http://localhost:8888/v1/service/health_check || exit 1
        interval: 5s
        timeout: 5s
        retries: 5

  redis:
    image: redis:6
    container_name: operations-agent-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
          test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
          interval: 5s
          timeout: 3s
          retries: 5

  # teams-bot:
  #   image: teams-bot
  #   container_name: team-bot
  #   restart: unless-stopped
  #   ports:
  #     - "3978:3978"
  #   environment:
  #     - NODE_ENV=production
  #     - MicrosoftAppId=your_app_id
  #     - MicrosoftAppPassword=your_app_password
  #   depends_on:
  #     - ems-service
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"